### ISSUE TITLE
Typing accents in latexbangla

### ISSUE THREAD

**Issue by mainakk** [Neehan/latexbangla#1]
It seems it is not possible to type accented Latin letters either directly or using escape sequences when latexbangla is used. An example code:

```
\documentclass{article}
\usepackage[banglamainfont=Kalpurush, banglattfont=Siyam Rupali]{latexbangla}
\usepackage{fontspec}

\begin{document}
%Erdős

%Erd\H os

%Erd\begin{latin}\H o\end{latin}s
\end{document} 
```

Uncommenting the first form gives an error: `\begin{latin} on input line 6 ended by \end{document}. \end{document}`
Uncommenting the second form produces an incorrect output.
The third form is a workaround I found, but it is a bit cumbersome to type every time.

My xelatex version: `XeTeX 3.14159265-2.6-0.99998 (TeX Live 2017/W32TeX)`

latexbangla version (from latexbangla.sty): `2016/10/31 v0.2 Enhanced LaTeX integration for Bangla`

**Comment by Neehan** [comment]
Here is a temporary remedy.
```
\documentclass{article}
\usepackage[banglamainfont=Kalpurush, 
            banglattfont=Siyam Rupali]
            {latexbangla}
% to allow escape sequence
\newcommand{\esc}[1]{\uccoff\fontfamily{lmr}\selectfont#1\uccon}

\begin{document}
Erd\esc{\H o}s
\section{Erd\esc{\H o}s}
\section{\texorpdfstring{Erd\esc{\H o}s}{Erdos}}
\end{document} 
```
`Erd\esc{\H o}s` will be fine in most cases, eg, inside paragraphs. However, it will produce warnings inside commands that generate bookmarks, for instance `section`. The output is still fine, but if the warnings bother you, try the third approach inside those commands.

LaTexbangla internally uses ucharclass package to identify latin letters, which are rendered by the Latin Modern font. From your output, it seems like ucharclass is not recognizing ő as a latin letter. This is probably a bug in ucharclass package, and unless the devs fix it there, I can't provide any permanent fix.
